spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth/server/**
          filters:
            - StripPrefix=2
        - id: offer-server
          uri: lb://offer-server
          predicates:
            - Path=/offer/server/**
          filters:
            - StripPrefix=2
  profiles:
    active: local
management:
  endpoints:
    web:
      exposure:
        include: "*"
ribbon:
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 5000  # 请求处理的超时时间
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试